services:
  mysql:
    image: mysql:8.0
    container_name: panaderia_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: panaderia
      MYSQL_USER: panadero
      MYSQL_PASSWORD: pan1234
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - panaderia_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=1
 
volumes:
  panaderia_data:
